"""Adicionando coluna permissao

Revision ID: 546276d3c0c0
Revises: 8c039f376b0b
Create Date: 2025-02-03 11:54:35.396848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546276d3c0c0'
down_revision = '8c039f376b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissao', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('permissao')

    # ### end Alembic commands ###
