"""Mudanca na models.py

Revision ID: 91d8ce8c8a8c
Revises: 5aa1ccd34117
Create Date: 2025-02-04 11:02:42.744385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91d8ce8c8a8c'
down_revision = '5aa1ccd34117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
