"""Mudanca na models.py

Revision ID: 9acf05cbfe39
Revises: d99a9bf2c189
Create Date: 2025-02-04 10:46:18.673933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acf05cbfe39'
down_revision = 'd99a9bf2c189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
