"""Mudanca na models.py

Revision ID: a8c3b39afd38
Revises: 532e4f7e8ec7
Create Date: 2025-02-04 10:59:16.966996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8c3b39afd38'
down_revision = '532e4f7e8ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
