"""Nova coluna tabela Usuarios

Revision ID: d99a9bf2c189
Revises: 941d6cb8a597
Create Date: 2025-02-03 13:38:55.769480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99a9bf2c189'
down_revision = '941d6cb8a597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissao', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('permissao')

    # ### end Alembic commands ###
