"""Mudanca na models.py

Revision ID: db10e42450c5
Revises: be68a07dfd13
Create Date: 2025-02-04 10:51:34.824423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db10e42450c5'
down_revision = 'be68a07dfd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
