"""Mudanca na models.py

Revision ID: e71c0cc3a092
Revises: 268c3a14cbc8
Create Date: 2025-02-04 11:03:59.121032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e71c0cc3a092'
down_revision = '268c3a14cbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
